Feature/78 implementacin de compra del carrito
G12-ISPP/ISPP pull request #129
Opened 2024-02-28 18:06 UTC by jucamgar2

Implementación de la compra del carrito #78 

### Descripción
Se ha implementado la pasarela de pago para comprar el carrito y se ha añadido una pestaña de detalles del pedido

### Contexto Adicional

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-02-28 20:10 UTC, davra02 reviewed
Se deberían migrar los componentes a la 
última versión de react, para mantener coherencia y estar actualizados, minimizando así los riesgos de incompatibilidades y fallos.

2024-02-28 21:23 UTC, davcorrom requested changes
He estado revisando la funcionalidad de compra del carrito y me he encontrado con algunos problemas en las pruebas que he realizado:

- Cuando meto productos en el carrito, se mantienen en él todo el rato a no ser que los quite. Da igual que cierre sesión de la cuenta, que inicie sesión con otra o lo que sea, que no se van los productos del carrito.
- En relación al problema anterior, me salta un error al darle al botón de comprar. En mi caso, he probado añadiendo productos al carrito desde una cuenta, luego he cerrado la sesión y he iniciado sesión con otra cuenta. Los productos permanecían en el carrito y al proceder con la compra, salta un error que impide acceder a la pasarela de pago. Desde ese punto, no he podido proceder con la compra en ningún momento, da igual inicie sesión con la cuenta que sea o incluso sin iniciar sesión.
- Por otra parte, otro problema ha sido que al proceder con el pago en un carrito y acceder a la pasarela de pago, si dentro de ella vuelvo hacia atrás y no termino el pago, el stock de los productos se reduce igualmente sin haber terminado la compra.
- Por último, habría que quitar el mensaje de stock para los diseños, puesto que los diseños no se agotan y al comprar uno no se reduce el stock, así que dicho texto no es necesario.

Quitando estos problemas que he encontrado, la funcionalidad tiene muy buena pinta y seguro que va a quedar perfecta.

2024-02-29 07:52 UTC, jucamgar2 commented
Gracias por tu review David, por eso mismo, voy a subir cambios intentando corregir todo lo que me has comentado, 

- En primer lugar ya no saltará mensaje de stock en los diseños y además cuando compres un diseño, su stock no se descontará.
- En segundo lugar, ahora se cambia el stock de los productos solo tras el pago.
- Por último, ahora cuando cierres sesión el carrito se vaciará

2024-02-29 09:04 UTC, davcorrom approved these changes
Me parecen fantásticas las correcciones realizadas, la funcionalidad ha quedado realmente bien y se pueden comprar productos perfectamente. ¡Enhorabuena!

2024-02-29 09:09 UTC, alegarsan11 approved these changes
Cambios perfectos, funcionalidad completa

2024-02-29 09:15 UTC, davra02 approved these changes
Gracias por las correciones aplicadas. El carrito ahora funciona correctamente.

2024-02-29 11:09 UTC, merged