Feat/65 chat entre usuarios
G12-ISPP/ISPP pull request #149
Opened 2024-02-29 22:13 UTC by davra02

## Chat entre 2 usuarios #65 

### Descripción

Implementación del chat entre 2 usuarios cualesquiera del sistema.

### Contexto Adicional

Se accede a través de la vista de un usuario

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-01 16:09 UTC, alegarsan11 approved these changes
Funcionalidad completa, Enhorabuena David

2024-03-02 14:09 UTC, davra02 commented
Muchas gracias por el feedback, los cambios que he introducido son:

- Formulario de envío de mensaje adaptado al tamaño de la ventana de mensajes y dentro de la misma
- Botón de volver a la vista de usuario
- Scroll automático al enviar un mensaje o al cargar el componente
- Se ha hecho algo más grande la ventana del chat

2024-03-02 19:19 UTC, davra02 commented
He comprobado las fallas de seguridad que lanzaba sonarcloud, y todas estaban contempladas en el código así que cambié su estado dando la explicación adecuada.

2024-03-03 12:44 UTC, diegarlin requested changes
Quizás estaría bien que apareciera en algún lugar con quien estás hablando arriba o algo así, y si pulsas encima del nombre en el chat te llevara a los detalles de ese usuario. Si es posible. Solo esas cosillas por lo demás todo está genial David. Enhorabuena por el trabajazo.
![image](https://github.com/G12-ISPP/ISPP/assets/92045874/9c0ccdb6-30e6-4eda-9825-6089c87fe579)

2024-03-03 22:13 UTC, davra02 commented
Gracias por el feedback @diegarlin , lo he tenido en cuenta, además de  paso he  arreglado otros estilos, y a mi juicio, ya ha quedado estupendo.  El tema de la redirección no era necesaria porque ya está el botón volver para eso.

2024-03-03 22:28 UTC, jucamgar2 commented
Ahora que he visto estos nuevos cambios David, muy buen trabajo, ha quedado fenomenal el chat, has hecho un gran trabajo y muy buen trabajo también por parte de los revisores que han propuesto mejoras

2024-03-03 22:43 UTC, PabloMera6 approved these changes
Perdón por la tardanza en la revisión de esta pull request, está bastante currada y con los cambios que han propuesto se nota mucho la mejora, enhorabuena David porque le da bastante valor a nuestro negocio.

2024-03-04 08:35 UTC, diegarlin approved these changes

2024-03-04 08:35 UTC, merged