Feat/143 mejorar diseño de la vista resumen de pedido
G12-ISPP/ISPP pull request #151
Opened 2024-03-01 11:10 UTC by carloosbaquero

##  Mejorar diseño de la vista resumen de pedido#143

### Descripción

Se han implementado los cambios pertinentes para que aparezcan los productos en el resumen de pedido, y se han aplicado estilos.

### Contexto Adicional

Intencionalmente vacío.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-01 11:14 UTC, carloosbaquero commented
<img width="514" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/3092c677-7393-43aa-a7dc-7efbb7940d0e">

2024-03-01 11:14 UTC, carloosbaquero commented
<img width="465" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/0df77a04-86a8-4e8e-9a9f-d33534d40a03">

2024-03-01 14:19 UTC, jucamgar2 approved these changes
Muy buen trabajo Carlos, me gusta como han quedado los detalles de los pedidos

2024-03-02 16:54 UTC, PabloMera6 commented
Hay un console.log(datos.buyer) que creo que se te ha olvidado eliminar, sería buena práctica eliminarlo para que no muestre los datos del comprador en la consola. Lo de añadir ceros al código postal no entiendo realmente por qué es, pero supongo que no tendrá que ser llamada nunca debido a que los códigos postales siempre tienen 5 números.

2024-03-02 17:00 UTC, PabloMera6 requested changes
Intenta mejorar lo que he mencionado anteriormente en el comentario Carlos, por lo demás buen trabajo!

2024-03-02 18:58 UTC, carloosbaquero commented
> Hay un console.log(datos.buyer) que creo que se te ha olvidado eliminar, sería buena práctica eliminarlo para que no muestre los datos del comprador en la consola. Lo de añadir ceros al código postal no entiendo realmente por qué es, pero supongo que no tendrá que ser llamada nunca debido a que los códigos postales siempre tienen 5 números.

Sobre lo de añadir ceros, el código postal puede ser menor de 10000 porque el de mi pueblo es 06228. Hay que arreglar eso en la validación del frontend, ya la arreglé yo en el backend. Sobre el console.log tienes razón, en cuanto pueda lo elimino

2024-03-03 12:21 UTC, diegarlin approved these changes
Me ha gustado la vista Carlos. Enhorabuena.

2024-03-03 12:23 UTC, PabloMera6 approved these changes
Perfecto Carlos, ahora entiendo el porqué del cambio en el código postal, buen trabajo!

2024-03-03 12:25 UTC, merged