Feature/193 feature subir opinión
G12-ISPP/ISPP pull request #239
Opened 2024-03-09 16:25 UTC by mariaescalante

## Formulario para subir opinión sobre un usuario #193 

### Descripción

Se ha implementado un formulario con el fin de que los usuarios puedan publicar opiniones sobre otros usuarios

### Contexto Adicional

Este formualario se encuentra en la página de detalles de cada usuario:
![image](https://github.com/G12-ISPP/ISPP/assets/73230133/321713c6-5b92-461f-83db-f2bdd1c072ac)
![image](https://github.com/G12-ISPP/ISPP/assets/73230133/8f0bd908-5673-462c-81eb-0bf1d4ec53f0)

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [x] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-09 17:23 UTC, alegarsan11 approved these changes
Bien trabajado Maria la funcionalidad se comporta como se esperaba.

2024-03-09 18:17 UTC, diegarlin reviewed
Quizás no pondría el formulario en la página de detalles de usuario sino un botón para que te llevara a otra o te saliera un overlay pero la funcionalidad se ejecuta correctamente.

2024-03-09 18:24 UTC, diegarlin approved these changes

2024-03-09 18:35 UTC, jucamgar2 requested changes
María, muy buen trabajo, pero me gustaría que para las validaciones, usases mensajes de error en vez de alertas, al igual que se hace en el formulario de custom_design, este te puede servir de ejemplo para copiar la lógica de validaciones.

2024-03-10 17:06 UTC, alesanfe approved these changes
Tengo algunas sugerencias:
1. Como señaló anteriormente @jucamgar2, la gestión de validaciones podría mejorarse.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/506173f9-8304-4cb7-a569-88f59d041bf2)
2. El campo de descripción es demasiado pequeño y se ve mal cuando se desplaza.![image](https://github.com/G12-ISPP/ISPP/assets/72869496/5e6efd78-0055-4bb8-b5dd-1456eb120568)
3. En mi opinión, sería buena idea agregar una imagen para mostrar el resultado.

2024-03-10 17:07 UTC, alesanfe requested changes
Me equivoqué al pulsar antes.

2024-03-10 22:18 UTC, alesanfe approved these changes
¡Genial, ahora sí! ¡Buen trabajo!

2024-03-10 22:42 UTC, PabloMera6 requested changes
He comprobado y parece que se comporta adecuadamente, pero me han surgido errores que no sé si son míos al traerme la rama debido a que nadie lo ha comentado anteriormente y me parece extraño. 
![error](https://github.com/G12-ISPP/ISPP/assets/72499392/2feb412e-297b-409d-bd29-490cd901d49d)
En esta captura se ve como da un error de invalid json cuando pongo un número con decimales y se ve el formulario de descripción y puntuación fuera del cuadro que los rodea. Por lo demás, considero que funciona adecuadamente.

2024-03-10 23:52 UTC, mariaescalante commented
Gracias a todos por los comentarios, ya debería estar todo arreglado y correcto

2024-03-11 12:48 UTC, Alejandrocg024 approved these changes
Estan corregidos los cambios solicitados y parece que todo funciona correctamente:

![image](https://github.com/G12-ISPP/ISPP/assets/72875687/1d3b0a00-8cf6-48a7-b467-e39f8e4d4ab4)

2024-03-11 12:48 UTC, Alejandrocg024 commented
Lo que no logro encontrar es donde ver las opiniones que se han publicado de ese usuario

2024-03-11 14:15 UTC, jucamgar2 approved these changes
Ahora sí, todo está perfecto, ¡Buen trabajo María!

2024-03-11 14:17 UTC, PabloMera6 approved these changes
Ya está todo arreglado como se aconsejó anteriormente, enhorabuena María!

2024-03-11 14:42 UTC, merged