Feat: Añadida funcionalidad de compra de planes
G12-ISPP/ISPP pull request #240
Opened 2024-03-09 17:06 UTC by jucamgar2

Compra de planes #185 

### Descripción

Se ha añadido la funcionalidad para que un usuario pueda comprar uno o varios planes

### Contexto Adicional

Si ya se ha comprado un plan, este no se puede vovler a comprar

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-09 18:23 UTC, diegarlin reviewed
Quizás mejoraría un poco la página de compra de planes ya que pone queiras y los estilos son un poco rústicos. Por lo demás la funcionalidad va perfectamente. Enhorabuena Juan Jesús!!

2024-03-09 18:23 UTC, diegarlin approved these changes

2024-03-09 18:40 UTC, jucamgar2 commented
Gracias por la corrección @diegarlin lo acabo de cambiar, en cuanto a los estilos tenía pensado mejorarlos más adelante, pero me interesaba subir ya la funcionalidad porque así se podrán empezar a implementar las funcionalidades de los diferentes planes.
Además también estaba esperando al customer agreement para hacer alguna referencia a el.

2024-03-10 16:53 UTC, alesanfe approved these changes
Todo bien, pero tal vez en el futuro estaría bien que se pareciera un poco más a esto.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/ebc2d99d-ff88-44af-b14c-8490fddc8789)

Así sería más claro ver las diferencias entre cada plan y motivaría a elegir uno en particular.

2024-03-10 22:53 UTC, PabloMera6 requested changes
Funciona correctamente, pero creo que se podrían mejorar los estilos de la página, como posible mejora 
![error3](https://github.com/G12-ISPP/ISPP/assets/72499392/62e217c4-eb26-4980-9782-2b8c040b7aed)
me parece que el texto superior es excesivo, quizás pondría 2 o 3 palabras, o ninguna, ya que se entiende perfectamente con la tabla que has hecho, que está bastante bien. Como última propuesta de mejora, 
![error2](https://github.com/G12-ISPP/ISPP/assets/72499392/57f3effb-86c5-47da-b4a0-45c8418491bd)
podemos ver que la r y la casilla para seleccionar se pisan, se podría añadir un poco más de separación

2024-03-11 12:55 UTC, Alejandrocg024 approved these changes
Concuerdo con todo lo comentado, creo que se puede mejorar los estilos en un futuro pero funciona perfectamente

2024-03-11 14:45 UTC, jucamgar2 commented
La idea era que los estilos se mejoren en un futuro, esta tare es principalmente para crear la funcionalidad, la captura que ha enviado @alesanfe me parece una buena idea para tener como ejemplo de como nos puede quedar, pero mi idea es que preparen correctamente estos estilos cuando esté listo el customer agreement

2024-03-11 21:19 UTC, PabloMera6 approved these changes
Entiendo lo que me dices, en una futura issue se solucionará el tema de los estilos entonces.

2024-03-11 21:20 UTC, merged