Feature/227 Mis pedidos
G12-ISPP/ISPP pull request #243
Opened 2024-03-09 18:51 UTC by carloosbaquero

## Mis pedidos#227

### Descripción

Se ha implementado un botón en la página de inicio que solo aparece cuando el usuario está loggeado. Este botón lleva a una nueva página en la que se encuentran todos los pedidos que el usuario ha realizado.

### Contexto Adicional

Incluye cualquier contexto relevante o información adicional sobre la solicitud de extracción.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-09 18:58 UTC, jucamgar2 requested changes
Carlos, muy buen trabajo, pero necesito dos pequeñas mejoras, en primer lugar, si el usuario no ha iniciado sesión debería saltar una alerta indicando que no ha iniciado sesión y redireccionandolo al welcome
Y en cuanto al listado, me gustaría que en vez de poner una foto en el listado de pedido y que esa foto sea de uno de los productos que añadas una foto por defecto en todos los pedidos, dicha foto se la puedes pedir a alguna IA

2024-03-10 15:38 UTC, carloosbaquero commented
> Carlos, muy buen trabajo, pero necesito dos pequeñas mejoras, en primer lugar, si el usuario no ha iniciado sesión debería saltar una alerta indicando que no ha iniciado sesión y redireccionandolo al welcome Y en cuanto al listado, me gustaría que en vez de poner una foto en el listado de pedido y que esa foto sea de uno de los productos que añadas una foto por defecto en todos los pedidos, dicha foto se la puedes pedir a alguna IA

Lo del inicio de sesión no lo he hecho porque tengo otra issue de seguimiento de pedidos por id, así que voy a hacer que si no está con la sesión iniciada salga un buscador. Respecto a lo de la imagen, he visto que amazon pone la imagen de un producto del pedido, pero si consideras que es mejor otra imagen lo cambio

2024-03-10 15:55 UTC, carloosbaquero commented
<img width="498" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/e0e0a07b-a89c-4c81-a926-e7db606b9fbd">
Foto cambiada @jucamgar2

2024-03-10 16:20 UTC, alesanfe approved these changes
¡Funciona de maravilla! La única cosa que ya se había mencionado (lo de la imagen que me parece un poco raro), pero aparte de eso, todo está genial.

2024-03-10 17:53 UTC, jucamgar2 approved these changes
Muy buen trabajo Carlos, la imagen es importante para asegurarnos de que siempre se verá bien la imagen del listado, buen trabajo, quizás en un futuro pondría incluso el logo de shar3d como diciendo que este pedido es gracias a shar3d

2024-03-10 23:03 UTC, PabloMera6 approved these changes
Lo veo todo correcto, suscribo lo que han dicho anteriormente pero funciona todo correctamente, enhorabuena!

2024-03-11 09:34 UTC, merged