Feat: Primera versión de "mis chats"
G12-ISPP/ISPP pull request #247
Opened 2024-03-10 18:55 UTC by davra02

## Mis chats #172 

### Descripción

Funcionalidad que muestra todos los chats disponibles para el usuario

### Contexto Adicional

Los chats disponibles siempre se mostrarán con cualquier chats ya que tendremos un "sidebar" a la izquierda que, según el usuario que seleccionemos, navegaremos a el chat en cuestión

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-10 19:24 UTC, davra02 commented
Dejo para revisión  la funcionalidad básica de "Mis chats". Está bastante completa, aunque susceptible de cambios que reciba como solicitudes en el feedback.

2024-03-10 21:52 UTC, mariaescalante requested changes
Gran trabajo David, simplemente comentarte una cosita. Al hacer click en el botón Volver se queda en esta pantalla y no termina de cargar.
![image](https://github.com/G12-ISPP/ISPP/assets/73230133/0f288f78-2c7a-408a-b1f6-63678913cb57)

2024-03-10 22:24 UTC, alesanfe requested changes
Corregir el error que he comentado en User.jsx.

2024-03-10 22:24 UTC, alesanfe commented on frontend/src/components/User.jsx
> +    const petition = `${backend}/chat/chatroom/`;
La variable backend la defines en el useEffect, pero no en el habdleChatClick.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/472322d9-1bb2-4dea-bb18-6ab09560b2b9)

2024-03-11 12:37 UTC, davra02 commented
> Gran trabajo David, simplemente comentarte una cosita. Al hacer click en el botón Volver se queda en esta pantalla y no termina de cargar. ![image](https://private-user-images.githubusercontent.com/73230133/311546423-0f288f78-2c7a-408a-b1f6-63678913cb57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjA4NDYsIm5iZiI6MTcxMDE2MDU0NiwicGF0aCI6Ii83MzIzMDEzMy8zMTE1NDY0MjMtMGYyODhmNzgtMmM3YS00MDhhLWIxZjYtNjM2Nzg5MTNjYjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEyMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZDA3NTU5MDNkMDM5NTNiYTNjMDNiOGRlNDA3YWRmZWE0OTZlZDRhZWJhNTUyNDc0ZTBhNzdkNWNmMTEwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bHFxzpEKp4hw2EtCTJSuv1oRUcA27cKzTKVYk_6QZRo)

Muchas gracias María, lo tengo en cuenta, ya tengo en mente por qué ha pasado en el próximo fix lo arreglo.

2024-03-11 12:38 UTC, davra02 commented on frontend/src/components/User.jsx
> +    const petition = `${backend}/chat/chatroom/`;
> La variable backend la defines en el useEffect, pero no en el handleChatClick. ![image](https://private-user-images.githubusercontent.com/72869496/311548014-472322d9-1bb2-4dea-bb18-6ab09560b2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjA4NDYsIm5iZiI6MTcxMDE2MDU0NiwicGF0aCI6Ii83Mjg2OTQ5Ni8zMTE1NDgwMTQtNDcyMzIyZDktMWJiMi00ZGVhLWJiMTgtNmFiMDk1NjBiMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEyMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MmE3YmZkZjFkZWVhOGEzOTMwNmJmMGNjMTc0YmFkYjBmNWZjMzBkMmRlYmVhMjY1YTQzMzQ3N2JjMGUzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JENrm6JuYAiyQgiELRTtdtjW39HnmZfCiM67pVsM_Ms)

Gracias Alejandro, se me debe haber paasado instanciar la referencia, también lo arreglo para el próximo fix.

2024-03-11 13:01 UTC, Alejandrocg024 commented
David como posible mejora, te comento que quizas sería mejor visualmente en vez de en la **nav-bar**, un icono de un chat en el **header**. Algo parecido a lo que tenemos con el carrito. No sé como lo ves mejor.

2024-03-12 22:23 UTC, diegarlin approved these changes
Está todo muy bien como pegas lo que te han dicho los otros compañeros nada más lo arregles mergea que es una gran feature par nuestra aplicación. Enhorabuena!!

2024-03-13 21:42 UTC, alesanfe commented on frontend/src/components/User.jsx
> +    const petition = `${backend}/chat/chatroom/`;
Recomiendo arreglarla cuanto antes ya que sin ella el botón de Chat en los detalles de usuario no va (está relacionado con esta funcionalidad).

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/8d49d470-3470-4cc1-9edd-7c06f020faf9)

2024-03-16 13:20 UTC, davra02 commented
> r

Me gusta mucho la  idea Alejando, ¡Gracias!

2024-03-16 13:20 UTC, davra02 commented
> David como posible mejora, te comento que quizas sería mejor visualmente en vez de en la **nav-bar**, un icono de un chat en el **header**. Algo parecido a lo que tenemos con el carrito. No sé como lo ves mejor.

Me gusta mucho la idea Alejandro, ¡Gracias!

2024-03-16 13:21 UTC, davra02 commented
> Corregir el error que he comentado en User.jsx.

Gracias por mencionarlo, ya estaba contemplado para arreglarse, hoy mismo actualizaré con los arreglos.

2024-03-16 18:12 UTC, davra02 commented
He introducido los últimos fixes:

- Ya no hay problema al pulsar el botón de chat, redirige correctamente
- Tampoco ocurre el problema de que se quede la página cargando al pulsar el botón volver dentro de "Mis chats"
- Se ha cambiado la pestaña de "Mis chats" por un icono más visual en el header
- Se ha añadido validación de autenticación: Se redirige al login si intentas acceder a algún tipo de vista de chats

2024-03-17 09:56 UTC, alesanfe approved these changes
- **Primer cambio:** Todo funciona perfectamente, aunque sería recomendable abordar el manejo del error 404 en el futuro.

https://github.com/G12-ISPP/ISPP/assets/72869496/3fbdd984-1769-4b96-ada6-44cde19760d6

- **Segundo cambio:** La funcionalidad es impecable. Realicé una prueba accediendo directamente a la URL para verificar si redirigía a la página principal (MAIN) o si mostraba un indicador de carga (LOADING).

https://github.com/G12-ISPP/ISPP/assets/72869496/2f061603-03a4-4a34-afd4-2145df938517

- **Tercer cambio:** Se ve muchísmo mejor.

- **Cuarto cambio:** Todo está en orden, aunque sería conveniente revisar el error. Sin embargo, no parece ser un problema importante ya que la aplicación funciona perfectamente incluso cuando ocurre.


https://github.com/G12-ISPP/ISPP/assets/72869496/94eb50e8-44ae-4519-af71-467b2e85fbf0

2024-03-17 11:49 UTC, davra02 commented
> * **Primer cambio:** Todo funciona perfectamente, aunque sería recomendable abordar el manejo del error 404 en el futuro.
> 
>  Vite.+.React.Mozilla.Firefox.2024-03-17.10-43-50.online-video-cutter.com.mp4 
> * **Segundo cambio:** La funcionalidad es impecable. Realicé una prueba accediendo directamente a la URL para verificar si redirigía a la página principal (MAIN) o si mostraba un indicador de carga (LOADING).
> 
>  Vite.+.React.Mozilla.Firefox.2024-03-17.10-48-47.online-video-cutter.com.mp4 
> * **Tercer cambio:** Se ve muchísmo mejor.
> * **Cuarto cambio:** Todo está en orden, aunque sería conveniente revisar el error. Sin embargo, no parece ser un problema importante ya que la aplicación funciona perfectamente incluso cuando ocurre.
> 
>  Vite.+.React.Mozilla.Firefox.2024-03-17.10-52-49.online-video-cutter.com.mp4

!Hola Alejandro! Muchísimas gracias por tu feedback tan detallado. 
Sobre el cuarto error, es totalmente normal, y de hecho me alegro de que ocurra, teniendo en cuenta que también hice validaciones en el back para que tuvieras que estar autenticados. Lo único que el cliente lo tenía que saber de alguna forma y no solo por el error en consola. 
Luego, sobre tu último comentario, tienes razón, se me ha debido olvidar borrar esa parte de código.

2024-03-17 12:31 UTC, PabloMera6 approved these changes
Muy guapo David, la funcionalidad también, has corregido todo lo que ha comentado Ale y funciona perfectamente.

2024-03-17 12:32 UTC, merged