Feature/229 Seguimiento de pedido
G12-ISPP/ISPP pull request #249
Opened 2024-03-11 11:51 UTC by carloosbaquero

## Seguimiento de pedido #229 

### Descripción

Se ha implementado un buscador de pedidos mediante id. Solamente se puede acceder a este buscador si no se está loggeado. Si se está loggeado aparecerán los pedidos realizados por el usuario, pero no el buscador.

### Contexto Adicional

Incluye cualquier contexto relevante o información adicional sobre la solicitud de extracción.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ x] He probado exhaustivamente estos cambios localmente.
- [x ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-11 11:55 UTC, carloosbaquero commented
<img width="485" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/68646762-f0c8-4770-9802-d83646890333">

<img width="605" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/a7921ae0-6886-436c-b4a5-a7dd7c0f4e1b">


<img width="387" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/793f20e3-336e-4aa0-a152-77f7403a7831">

<img width="398" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/6bfea0b8-c1b6-45ce-8c46-ae0aecaa5275">

2024-03-11 13:11 UTC, Alejandrocg024 requested changes
La funcionalidad funciona a la perfección pero unos pequeño detalles que no veo practicos. 

Para buscar tienes que pulsar en el icono de la lupa que personalmente pensaba que no era un icono. Contando que la aplicación puede ser para personas inexpertas creo que es conveniente añadir un simple boton debajo que diga algo así como "Buscar". 

Otro pequeño detalle es que el título de la página cuándo no estas logueado en vez de "Mis pedidos" quizas sería más adecuado que fuese algo así como "Buscar Pedidos", no sé como lo ves tu.

2024-03-11 15:17 UTC, davcorrom requested changes
He estado revisando la nueva funcionalidad y se me ocurren diferentes mejoras a realizar.

En primer lugar, estoy de acuerdo con Alejandro, estaría bien poner un botón para realizar la búsqueda y no que se haga pulsando en la lupa. También contemplaría ejecutar la acción de búsqueda al pulsar la tecla Intro.

Por otra parte, quitaría el botón de Pedidos del header cuando el usuario no ha iniciado sesión. Yo lo veo mejor incluirlo como una opción permanente en el footer, es decir, añadir algo así al componente footer.jsx, con su redirección correspondiente:

![image](https://github.com/G12-ISPP/ISPP/assets/73230994/bad52909-ea7d-4eda-8047-417055d8ebf4)

Luego, en todo caso, cuando esté lista la funcionalidad de perfil de usuario, sí estaría bien colocar el botón dentro del propio perfil, pero no en el header, que se queda muy sobrecargado.

Por otra parte, me he creado una cuenta nueva y he accedido a la sección de Pedidos. Entonces, como no he realizado ningún pedido, me pone el mensaje correspondiente y no puedo hacer nada, lo cual está correcto. Tras esto, he comprado un diseño. Luego he accedido al apartado de pedidos y me aparece el pedido triplicado, cuando solo debería aparecer una vez. Adjunto imagen con el pedido triplicado. Todos son el mismo pedido.

![image](https://github.com/G12-ISPP/ISPP/assets/73230994/34ac8b78-083d-4847-bfb0-410d4852d11d)

A pesar de estos detalles, considero que la funcionalidad tiene muy buena pinta y se guro que queda perfecta. ¡Buen trabajo!

2024-03-14 12:01 UTC, carloosbaquero commented
<img width="634" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/b950153a-426b-4ec5-9d60-d325cf2a1f0b">
He realizado todos los cambios solicitados por @Alejandrocg024 y @davcorrom .

Respecto al fallo de que aparecen 3 pedidos que ha comentado @davcorrom , creo que es por el error descrito en la issue #255   lo intentaré solucionar en otra pull request

2024-03-14 15:38 UTC, diegarlin approved these changes
Funciona bien, quizás dejaría que los usuarios logueados pudieran acceder al buscador y también a todos los pedidos que han comprado pero bueno hasta elmomento es una buena solución. Enhorabuena!!

2024-03-14 16:21 UTC, carloosbaquero commented
> Funciona bien, quizás dejaría que los usuarios logueados pudieran acceder al buscador y también a todos los pedidos que han comprado pero bueno hasta elmomento es una buena solución. Enhorabuena!!

Tienes razón, de que esté implementado el perfil de usuario se dividirá Mis pedidos de Seguimiento de pedido

2024-03-15 16:40 UTC, davcorrom approved these changes
Buen trabajo Carlos, me gusta cómo ha quedado la solución implementada finalmente. Ahora la cabecera no está sobrecargada con tantos botones y la interfaz de seguimiento de pedido me parece más intuitiva. ¡Enhorabuena!

2024-03-15 17:03 UTC, Alejandrocg024 approved these changes
Muy buen trabajo Carlos. Me gusta mucho como ha quedado.

2024-03-16 10:16 UTC, antcardia approved these changes
Has hecho un gran trabajo y añado lo mismo que comentaba @diegarlin anteriormente

2024-03-16 10:21 UTC, merged