Feat: Mi perfil de usuario
G12-ISPP/ISPP pull request #251
Opened 2024-03-11 17:54 UTC by Alejandrocg024

Se ha realizado todo el apartado para visualizar el perfil de usuario autenticado

  ## Mi perfil de usuario #180 

### Descripción

Se ha añadido en la barra superior un icono de usuario para acceder al perfil autenticado y poder ver los detalles. 

### Contexto Adicional

Para ello, se ha modificado el apartado de detalles de artistas, realizando algunas modificaciones visuales del mismo.:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/75c57101-8fb3-4fe5-829e-b7bae15d2e70)

Se ha realizado también la parte responsive:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/c98b4a9f-7b9c-46ea-841b-8bde633529f4)

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [X] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-11 20:08 UTC, antcardia approved these changes
Funciona a la perfección. Como detalle, acabo de subir una pull request añadiendo la lógica de subir una foto de perfil al registrarse un nuevo usuario, y cuando ambas estén aceptadas y mergeadas en la rama develop, puedo encargarme de mostrar la imagen guardada por el usuario en caso de que tuviera. ¡Buen trabajo!

2024-03-11 21:05 UTC, davcorrom requested changes
¡Muy buena funcionalidad Alejandro! La he estado probando y funciona todo bien, aun así, creo que es conveniente realizar algunos cambios para dejarlo todo a punto. Me gustaría, si es posible, que se quitase el botón de cerrar sesión cuando un usuario esté autenticado, de forma que tan solo tengamos el icono del perfil y que, al pulsar en él, apareciera un desplegable con dos opciones, una para ir al perfil y otra para cerrar la sesión. De esta forma hacemos que el header no esté tan sobrecargado. Dentro de ese desplegable se podría poner también la opción de _Pedidos_, o bien dentro del propio perfil, ya como mejor consideres. Menciono también la issue del seguimiento de pedidos, la cual sigue abierta por si existiera la posibilidad de que os coordinaseis para mover el botón de sitio, pues dejé un comentario comentando algo similar ahí (#249).

2024-03-13 16:55 UTC, diegarlin commented
@Alejandrocg024 esta issue tiene correlación con la issue que me está asignada #181, si es posible acabala lo antes que puedas parar poder empezar con la implementación de esta

2024-03-14 12:40 UTC, Alejandrocg024 commented
Muchas gracias a todos, se han implementado las distintas mejoras solicitadas:

> ¡Muy buena funcionalidad Alejandro! La he estado probando y funciona todo bien, aun así, creo que es conveniente realizar algunos cambios para dejarlo todo a punto. Me gustaría, si es posible, que se quitase el botón de cerrar sesión cuando un usuario esté autenticado, de forma que tan solo tengamos el icono del perfil y que, al pulsar en él, apareciera un desplegable con dos opciones, una para ir al perfil y otra para cerrar la sesión. De esta forma hacemos que el header no esté tan sobrecargado. Dentro de ese desplegable se podría poner también la opción de _Pedidos_, o bien dentro del propio perfil, ya como mejor consideres. Menciono también la issue del seguimiento de pedidos, la cual sigue abierta por si existiera la posibilidad de que os coordinaseis para mover el botón de sitio, pues dejé un comentario comentando algo similar ahí (#249).

David, lo he hecho de la siguiente forma, espero que te guste:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/d82f868b-3518-4396-be41-899e412e6432)



> Lo veo todo genial siguiendo los estilos de la aplicación lo único sería que cuando me deslogueo y entro en la misma ruta sigue apareciendo que estoy en mi perfil. Creo que el fallo está en el logout, cuando lo arregles te acepto y ya mergeamos. Gran trabajo Alejandro!!

Diego también he solucionado este fallo que se trataba del localStorage que no se actualizaba al cerrar sesión, adjunto prueba sin estar logueado como Alejandro Campano:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/f041f849-6542-4fda-92ec-7411a8f12f00)

2024-03-14 15:26 UTC, diegarlin approved these changes
Perfecto con todos los cambios que se te pidieron implementados!!

2024-03-14 17:08 UTC, jucamgar2 approved these changes
Que gran trabajo Campano, muy buen trabajo también por parte de los demás compañeros que han propuesto mejoras, ¡Enhorabuena!

2024-03-15 15:51 UTC, PabloMera6 approved these changes
Veo bastante bien la funcionalidad, además visualmente es atractiva. No he encontrado ningún error probando, buen trabajo!

2024-03-15 15:52 UTC, davcorrom approved these changes
Muy bien Alejandro, me gusta mucho cómo ha quedado la funcionalidad al final, además, la cabecera se ve mucho más limpia así, ¡enhorabuena!

2024-03-17 09:23 UTC, alesanfe approved these changes
No he encontrado ningún fallo y supuso una mejora visual que la aplicación necesitaba con urgencia. Solo quería mencionar que los tests de UserDetails fallan, pero eso es comprensible ya que simplemente están comprobando la interfaz después del cambio. Aparte de eso, todo está perfecto.

![Mejora Visual](https://github.com/G12-ISPP/ISPP/assets/72869496/81a32243-bbd7-4930-a5bf-d8ef727185b2)

2024-03-17 09:37 UTC, merged