Feat: Añadir foto de perfil en el registro
G12-ISPP/ISPP pull request #252
Opened 2024-03-11 19:57 UTC by antcardia

## Añadir lógica para subir foto en el registro #174 

### Descripción

Cuando una persona quiera registrarse, tiene la opción de subir una imagen para que sea usada como foto de perfil y que la pueda ajustar como prefiera.

### Contexto Adicional

Tiene la opción de no subir ninguna imagen de perfil si lo desea y, en caso contrario, debe tener en cuenta que las imágenes pesadas no son permitidas por el sistema.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-11 21:23 UTC, jucamgar2 commented
Quizás antonio, sería buena idea esperar a que la tarea del perfil de @Alejandrocg024 se mergee en develop para que puedas aprovechar y mostrar las fotos también en el apartado de perfil correctamente

2024-03-12 10:27 UTC, diegarlin approved these changes
La funcionalidad está genial Antonio, lo único que te diría es que en esta vista pusieras un botón si fuera posible de confirmación ya que no queda muy claro cuando la foto está seleccionada o no, por lo demás todo perfecto. Enhorabuena!!
![foto de perifl](https://github.com/G12-ISPP/ISPP/assets/92045874/e44d4f55-ce59-4a51-a9c7-7a7aa92d416b)

2024-03-12 10:45 UTC, diegarlin commented
También si puedes sube la migración del backend que no está subida por favor.

2024-03-12 17:22 UTC, alesanfe requested changes
He probado con .png funciona perfectamente, pero con .jpg como ves en el vídeo me da una excepción:

https://github.com/G12-ISPP/ISPP/assets/72869496/754e631d-b511-4498-a416-13f57f5b4fe7

2024-03-12 17:55 UTC, antcardia commented
En cuanto al botón de confirmación @diegarlin , lo había pensado poner, pero la librería que estoy usando no lo contempla, sino que directamente se muestra el cambio que realices en directo. En cuanto al error @alesanfe, voy a comprobarlo de nuevo porque yo no he tenido problemas con imágenes .jpg, pero voy a utilizar la imagen que me proporcionas para comprobarlo y corregirlo.

2024-03-12 19:23 UTC, antcardia commented
Ya debería estar arreglado @alesanfe. Faltaba mostrar un mensaje de error cuando la imagen es demasiado grande, como era este caso.

2024-03-12 20:24 UTC, alesanfe approved these changes
Efectivamente, el error se debía a que el archivo era demasiado grande. He disminuido su tamaño y ahora funciona perfectamente.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/d22ba3c7-3658-4f3d-893d-e774f40a75b8)

¡Gran trabajo, @antcardia!

2024-03-12 22:28 UTC, PabloMera6 approved these changes
Quizás la restricción del tamaño en las imágenes es necesario pero no me permite usar la mayoría de imágenes de las que dispongo, por lo demás la funcionalidad funciona perfectamente. Sin embargo, he comprobado el resto de páginas y he visto que algunos estilos no están bien. Creo que deberías traerte develop y comprobar que se arregla con eso, puesto que no has tocado CSS que puedan afectar 
![error4](https://github.com/G12-ISPP/ISPP/assets/72499392/351e466e-2035-48ce-902f-1a613d0e5dda)

2024-03-13 16:58 UTC, merged