Test/219 Conversión stl
G12-ISPP/ISPP pull request #267
Opened 2024-03-16 12:41 UTC by carloosbaquero

## Test Conversión stl#219 

### Descripción

En la realización del test me he dado cuenta de que la funcionalidad no funcionaba, así que la he arreglado y he hecho que solamente se puedan usar archivos menores a 10 mb, ya que si se usaban archivos muy grandes el backend se caía.

También se han realizado los tests pertinentes

### Contexto Adicional

Incluye cualquier contexto relevante o información adicional sobre la solicitud de extracción.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-16 17:15 UTC, jucamgar2 approved these changes
Bien hecho carlos, los test funcionan a la perfección, por lo que nos ayudarán a encontrar futuros fallos en la funcionalidad.
PD: Me encanta el detalle de que esta PR tenga 2 millones de líneas añadidas por los archivos obj jajajaja

2024-03-17 09:16 UTC, alesanfe approved these changes
# **Prueba:**

Salta el error correctamente:

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/13ebf699-e7cb-4098-99fa-e41631386138)

El fichero se genera sin problemas:

![Resultado Generado](https://github.com/G12-ISPP/ISPP/assets/72869496/eefbebdd-5e5c-4651-8b71-b3e12d4ca347)

# **Conclusión:**

Se han solucionado los problemas que había. A lo mejor, podríamos revisar el tamaño límite para convertir a formato STL, porque 10 MB puede ser un poco justo.

2024-03-17 09:27 UTC, alesanfe requested changes
¡Me acabo de acordar! Si subes archivos tan pesados, podríamos tener problemas durante el despliegue. Si no es inconveniente, ¿podrías eliminarlos?

2024-03-17 13:06 UTC, carloosbaquero commented
He eliminado el archivo de 80mb y he permitido subir archivos de hasta 30 mb

2024-03-17 22:22 UTC, antcardia approved these changes
Muy buen trabajo Carlos! Los test funcionan a la perfección.

2024-03-17 22:30 UTC, mariaescalante approved these changes
Enhorabuena Carlos, todos los tests funcionan exitosamente

2024-03-18 14:44 UTC, alesanfe approved these changes
Todo perfecto.

2024-03-18 14:44 UTC, merged