test: test sobre listado de productos
G12-ISPP/ISPP pull request #273
Opened 2024-03-17 12:25 UTC by diegarlin

## Test sobre el listado de productos #203

### Descripción

Tests sobre todas las páginas de listado 

### Contexto Adicional

No se puede comprobar que hay objetos dentro ya que vitest no renderiza la página entera, es decir si pones un productsGrid eso no se verá en el html que renderiza vitest, por lo tanto no puedo ver cuantos objetos hay dentro de la página ni nada.

Tampco tiene sentido probar en el backend ya que estas vistas solo llaman a la api y las rutas están predefinidas, es decir nadie ha creado una url y vista específico viene todo dado por la api rest de django.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [x] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-18 14:45 UTC, jucamgar2 requested changes
Diego, hecho en falta algúna prueba unitaria que vaya directamente al backend

2024-03-19 14:14 UTC, antcardia requested changes
Estaría bien añadir test de backend para que sea más completo.

2024-03-19 15:40 UTC, diegarlin commented
@jucamgar2 @antcardia Ya he implementado los tests de backend correspondientes

2024-03-19 21:26 UTC, jucamgar2 approved these changes
Muy buen trabajo Diego, gracias por tu rapidez ¡Buen trabajo!

2024-03-19 21:39 UTC, Alejandrocg024 approved these changes
Muy buen trabajo Diego!

2024-03-20 19:38 UTC, davra02 approved these changes
¡Buen trabajo Diego!, he ejecutado los test y funcionan correctamente, además que dan buena cobertura para el listado.

2024-03-21 11:11 UTC, antcardia approved these changes
Está perfecto con los test de backend

2024-03-21 11:14 UTC, merged