Feature/277 fix detalles de usuario
G12-ISPP/ISPP pull request #279
Opened 2024-03-17 18:36 UTC by ursgarsan

## Detalles de usuario corrección estilos #277

### Descripción

Se han corregido los estilos de la página de detalles de usuario.

### Contexto Adicional

Incluye cualquier contexto relevante o información adicional sobre la solicitud de extracción.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [x] He revisado y resuelto cualquier conflicto de fusión.
- [x] He actualizado la documentación.

2024-03-17 18:38 UTC, diegarlin approved these changes
Ahora se ve mucho mejor la página de detalles!!

2024-03-17 23:06 UTC, antcardia requested changes
He añadido opiniones de otros diseñadores o impresores y ha funcionado a la perfección, pero he probado a hacer una opinión a mi propio perfil y me han salido diferentes errores. Primero me aparecía como un error 403 Forbidden y no salía ningún mensaje en la página que avisara de que no puedo añadir una opinión sobre mí mismo y, después, me aparecía el mensaje "Opinión añadida correctamente" cuando finalmente no se añade nada. Habría que tener en cuenta de que no se añadan opiniones a uno mismo para evitar este error. Por lo demás, lo veo correcto.

2024-03-18 15:45 UTC, ursgarsan commented
> He añadido opiniones de otros diseñadores o impresores y ha funcionado a la perfección, pero he probado a hacer una opinión a mi propio perfil y me han salido diferentes errores. Primero me aparecía como un error 403 Forbidden y no salía ningún mensaje en la página que avisara de que no puedo añadir una opinión sobre mí mismo y, después, me aparecía el mensaje "Opinión añadida correctamente" cuando finalmente no se añade nada. Habría que tener en cuenta de que no se añadan opiniones a uno mismo para evitar este error. Por lo demás, lo veo correcto.

En esta issue únicamente se miran los estilos, esa lógica debe ser arreglada a la hora de crear opiniones, se arreglará próximamente en otra issue, te he vuelto a pedir la revisión ya una vez aclarado esto, gracias!

2024-03-18 19:56 UTC, PabloMera6 requested changes
He visto que puede haber un pequeño descuadre en cuanto a los estilos de los detalles, adjunto una imagen en la que se puede ver 
![errrr](https://github.com/G12-ISPP/ISPP/assets/72499392/0a0a2e7e-e08b-4eb3-b9a3-93ef03eff07c)
También pasa que la foto de perfil de los usuarios no aparece, pero creo que cuando resuelvas los confilctos en User.jsx se mostrará bien, ya que esta PR únicamente se encarga de los estilos 
![errr3](https://github.com/G12-ISPP/ISPP/assets/72499392/c7096e45-a3cf-4c44-a48a-eb886af4b7e7)
Por lo demás, todo perfecto, enhorabuena!

2024-03-18 22:00 UTC, PabloMera6 approved these changes
Parece que se ve mejor, pero aún así hace falta más correcciones en los estilos de esta vista, se puede plantear como futura issue debido a que el responsive falla

2024-03-18 22:02 UTC, merged