Feature/262 mejoras usurios pilotos 2
G12-ISPP/ISPP pull request #283
Opened 2024-03-17 20:54 UTC by carloosbaquero

## Mejoras usurios pilotos 2#262 

### Descripción

- Los detalles de impresor ya se mostraban
- Ahora el mensaje de deslogueo exitoso se ha cambiado por "Se ha cerrado sesión con éxito!!"
- Los botones de + y - ya estaban añadidos en el carrito
- Los títulos y campos de los productos ya estaban corregidos o yo al menos los he visto correctos
- Se ha añadido asterisco a los parámetros obligatorios de los formularios
- Se han añadido descripciones a los artistas/diseñadores

### Contexto Adicional

Incluye cualquier contexto relevante o información adicional sobre la solicitud de extracción.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-17 20:56 UTC, carloosbaquero commented
<img width="505" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/b0fecb67-5f7a-4aa6-a099-ba3505ee245b">

<img width="365" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/2f7c7995-af4a-439c-90fc-95369719d025">
<img width="416" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/ec90efe4-b09d-41a3-af97-347ea69d0fa1">

2024-03-17 22:42 UTC, antcardia requested changes
He estado probando todo lo que has implementado y está muy bien, pero me parece que, a la hora de añadir el campo descripción cuando se hace el registro como diseñador, se expande demasiado. Como posible mejora, reduciría un poco el tamaño de la descripción. Por lo demás lo veo genial!

![image](https://github.com/G12-ISPP/ISPP/assets/72875624/b1fc2aad-d92e-4e29-8952-b4905cef21e6)

2024-03-18 14:52 UTC, jucamgar2 requested changes
Carlos en cuanto a la mejora:
- Los botones de + y - ya estaban añadidos en el carrito
En el la base de conocimiento https://knowledge-base-orpin.vercel.app/docs/Evaluaciones/Propuestas%20de%20mejora%20UP%20Sprint%201
Se comenta lo que tu dices de que ya estaban, pero se proponía cambiar el color del número ya que no es muy posible, por favor, realiza esta modificación y la PR será mergeada
En cuanto al resto, ¡buen trabajo!

2024-03-18 14:58 UTC, Alejandrocg024 commented
> Carlos en cuanto a la mejora:
> 
> * Los botones de + y - ya estaban añadidos en el carrito
>   En el la base de conocimiento https://knowledge-base-orpin.vercel.app/docs/Evaluaciones/Propuestas%20de%20mejora%20UP%20Sprint%201
>   Se comenta lo que tu dices de que ya estaban, pero se proponía cambiar el color del número ya que no es muy posible, por favor, realiza esta modificación y la PR será mergeada
>   En cuanto al resto, ¡buen trabajo!

La tarea de los botones + y - en el carrito la estoy realizando yo en la issue #177

2024-03-18 15:00 UTC, Alejandrocg024 approved these changes
He estado probando los nuevos cambios y los veo bastante bien hechos

2024-03-20 09:31 UTC, carloosbaquero commented
<img width="387" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/14abd0c2-7b62-4065-876a-000471106eb2">
@antcardia ya he empequeñezido el campo descripción
@jucamgar2 sobre tu comentario ya escribió @Alejandrocg024 que se encargaría él

2024-03-20 15:46 UTC, antcardia approved these changes
Ahora el campo de la descripción está mucho mejor. ¡Buen trabajo!

2024-03-21 11:07 UTC, jucamgar2 approved these changes
Buen trabajo Carlos, ahora si está todo como debería. ¡Enhorabuena!

2024-03-21 11:32 UTC, merged