Feature/263 mejoras usuarios piloto 3
G12-ISPP/ISPP pull request #285
Opened 2024-03-18 17:44 UTC by alesanfe

## Mejoras Usuarios piloto 3 #263

### Descripción

Se han implementado las siguientes mejoras:
- Mensajeal inicio que explica cual es el objetivo de la aplicación.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/011cdf57-cb73-4fb3-849d-2906ac825923)
- Mensaje que explica como funciona el visualizador.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/f1fd23f6-535d-4b5e-ad14-d44df0296918)
- Un Zoom (el coom te lo hace cunado pinchas)
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/fee037f7-1e4c-457e-8549-a3a9c20d7654)
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/795a8217-3a00-4c4e-aad1-fe336c43f884)
- Y unas restricciones de mínimos y máximos para usuario, correo, ciudad y dirección.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/6922bc06-183c-4579-a6fb-721b4a981edb)

### Contexto Adicional

_No procede_

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-18 20:52 UTC, jucamgar2 approved these changes
Que gran trabajo Alejandro, todo funciona perfecto y sobre todo, lo has resuelto muy rapido, ¡Enhorabuena!

2024-03-19 12:12 UTC, diegarlin requested changes
Sobre los mensajes y las restricciones todo correcto, lo único es que el zoom en mi ordenador no funciona da igual que ponga más o menos no se si es error mío que puede ser ya que veo que ha aprobado los cambios un compañero. Por otra parte, en el archivo customDesign.jsx hay un error que adjunto en la imagen y cuando runeo en localhost no me deja, por si pudieras cambiar los : por un ;.

![image](https://github.com/G12-ISPP/ISPP/assets/92045874/882f093f-7e3c-4ee3-8c16-43cb6fe358bc)

2024-03-19 12:35 UTC, alesanfe commented
> Sobre los mensajes y las restricciones todo correcto, lo único es que el zoom en mi ordenador no funciona da igual que ponga más o menos no se si es error mío que puede ser ya que veo que ha aprobado los cambios un compañero. Por otra parte, en el archivo customDesign.jsx hay un error que adjunto en la imagen y cuando runeo en localhost no me deja, por si pudieras cambiar los : por un ;.
> 
> ![image](https://private-user-images.githubusercontent.com/92045874/314047352-882f093f-7e3c-4ee3-8c16-43cb6fe358bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTE5MjcsIm5iZiI6MTcxMDg1MTYyNywicGF0aCI6Ii85MjA0NTg3NC8zMTQwNDczNTItODgyZjA5M2YtN2UzYy00ZWUzLThjMTYtNDNjYjZmZTM1OGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEyMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYmQzY2M3MjYyZDNhZDE4ZTY1YzFiZWE3Y2FjNTRiODJlYzFhODgxMWE1M2VkOTMxZWNjNDQxYmQwYzdjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s88kgAFnEqUTjnM5DzZCLTvHGtTuYQTle8abJQRWkpg)

Respecto a lo del Zoom, hace el zoom cuando se pulsa con el ratón en el visualizador (es un poco extraño) y lo otro es un despiste al solucionar los conflictos.

2024-03-19 15:51 UTC, diegarlin approved these changes
Ahora sí, un poco raro la funcionalidad del zoom pero es verdad que pulsando zoomea. Enhorabuena!!

2024-03-19 21:43 UTC, Alejandrocg024 approved these changes
Muy buenas mejoras, felicidades!

2024-03-19 22:27 UTC, merged