(feature) Chat Responsive
G12-ISPP/ISPP pull request #298
Opened 2024-03-20 19:33 UTC by davra02

## Chat  Responsive #254

### Descripción

Se ha rediseñado la interfaz del chat para dispositivos móviles haciéndola responsive

### Contexto Adicional

La anchura a partir de la cual comienza este cambio de estilos es 1300px, para una anchura mayor se considerará el estilo estándar.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-03-20 19:50 UTC, davra02 commented
Se ha terminado por ahora el apartado responsive del chat. Todo feedback es bienvenido. En principio hay poco punto de fallo en esta "feature", pero si veis algún tipo de dimensión que haya que cambiar o si en cierto punto el estilo se comporta de forma rara, no dudéis en comunicarlo.

2024-03-20 19:57 UTC, davra02 commented
Puntos a probar la interfaz para dispositivos móviles:

- Cuando se pasa de la dimensión mínima establecida (width: 1300px), el footer se eliminará y el chat se adaptará a toda la pantalla.
- Del mismo modo, el side-bar pasará a modo "togle", el cual podremos activar con un botón que contiene una flecha.

2024-03-21 08:34 UTC, diegarlin requested changes
Está muy bien el responsive del chat me ha gustao mucho tanto la implementación como el resultado. Ha quedado muy clean. Lo único sería que quitaras algunos mensajes que salen en la consola y un par de errores que no creo que sean muy rápidos de arreglar.
![image](https://github.com/G12-ISPP/ISPP/assets/92045874/fe057693-92b2-4c84-871f-b0fc8267ac41)

2024-03-21 10:19 UTC, davra02 commented
> Está muy bien el responsive del chat me ha gustao mucho tanto la implementación como el resultado. Ha quedado muy clean. Lo único sería que quitaras algunos mensajes que salen en la consola y un par de errores que no creo que sean muy rápidos de arreglar. ![image](https://private-user-images.githubusercontent.com/92045874/315211424-fe057693-92b2-4c84-871f-b0fc8267ac41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTY1MzMsIm5iZiI6MTcxMTAxNjIzMywicGF0aCI6Ii85MjA0NTg3NC8zMTUyMTE0MjQtZmUwNTc2OTMtOTJiMi00Yzg0LTg3MWYtYjBmYzgyNjdhYzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEwMTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNjM0YzAwMWMxYWJkYTkxODRhNzMyZGIxZDYxNDI4MGRkNWU3NWU2ZGYxNWE4MGVlODFmMDg5NzBhMDcxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2tWUIOYbpx8m20nQgTt1oXcQo5v2zq4hV4Yd3OoiCA)

Gracias Diego, ese error que sale es totalmente normal, no es un fallo de la aplicación como tal ya que está contemplado, pero es cierto que queda más limpia la consola y con menos confusión capturo la excepeción. Gracias por el recordatorio.

2024-03-21 16:42 UTC, davcorrom requested changes
David, he entrado en la rama donde has realizado los cambios y he visto que ha dejado de funcionar el scroll de la página. Por lo que he podido ver, se trata del siguiente estilo que has incorporado en _ChatComponent.css_:

![image](https://github.com/G12-ISPP/ISPP/assets/73230994/2edf803f-f316-4bf9-924d-60aee25dc8e2)

Con eso estás haciendo que no se vea nada si se sale por debajo de la pantalla, impidiendo el scroll.

2024-03-21 18:13 UTC, jucamgar2 approved these changes
Que bien David, ha quedado perfecto, ahora el chat no solo funciona a la perfección, sino que se ve perfectamente en todo tipo de dispositivos ¡enhorabuena!
![image](https://github.com/G12-ISPP/ISPP/assets/72499336/a23392a3-4b5b-41bb-9410-9316ea6203cf)

2024-03-21 18:18 UTC, diegarlin approved these changes
Enhorabuena David por la feature y el diseño!!!

2024-03-21 19:30 UTC, davcorrom approved these changes
Enhorabuena, David. Los cambios, ahora sí, están perfectos. Ha quedado muy bien la funcionalidad. ¡Buen trabajo!

2024-03-21 19:32 UTC, merged