Feature/366 mejoras up s3 6
G12-ISPP/ISPP pull request #395
Opened 2024-04-08 16:18 UTC by diegarlin

## Mejoras de usuario 6 #366

### Descripción

- id-33
 He reorganizado el escaparte principal  y puesto los botones de cambiar a STL, comprar plan y solicitar impresión en el header. Adjunto imágenes del antes y después:
Antes:
![imagen1](https://github.com/G12-ISPP/ISPP/assets/92045874/f351f4fc-7465-4249-b137-68e1e5ff0ab9)

Después:
![image](https://github.com/G12-ISPP/ISPP/assets/92045874/9b311e2d-6f01-48fb-bb36-f809681ee9a7)

![image](https://github.com/G12-ISPP/ISPP/assets/92045874/c1cc4d00-8598-471e-8ecb-ffa84be86da8)

- id-36
 Ahora en el registro sale un campo en el cual tienes que confirmar la contraseña y se han implementado las validaciones correspondientes:
![image](https://github.com/G12-ISPP/ISPP/assets/92045874/ee636169-0ddc-4c0e-8622-c22c6a222c66)

- id-37
 Validación para no poder poner varias reseñas sobre el mismo usuario con una misma cuenta:
 
![image](https://github.com/G12-ISPP/ISPP/assets/92045874/31ebc5ab-d328-4b3b-9ee9-905e6de22d95)

 

### Contexto Adicional

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [x] He revisado y resuelto cualquier conflicto de fusión.
- [x] He actualizado la documentación.

2024-04-08 18:01 UTC, alesanfe requested changes
- Respecto a la primera, se ha roto un poco la separación entre botones.
  - Antes
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/613ac37f-b143-4a33-baf7-454e3bf268f8)
  - Después  
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/e116ae3e-2f57-44f1-b056-173eac3bf0f3)

- Respecto a la segunda, funciona perfectamente.

- Respecto a latercera, funciona correctamente.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/a7e13e02-187e-4841-a19a-c57817eb1ed0)

Algo que me gustaría mencionar es que al haberse modificado, el Main, ahora el test no va, recomendaría que lo arreglases, es un test muy simple si no me equivoco.

2024-04-08 18:02 UTC, alesanfe commented
Una vez cambies lo de la primera te lo acepto.

2024-04-09 11:15 UTC, diegarlin commented
@alesanfe Ya he cambiado lo que me has dicho. Muchas gracias no me había dado cuenta ni de lo estilos de los botones ni de el error en los tests, además he actualziado la rama con los cambios de develop.

2024-04-09 13:00 UTC, jucamgar2 approved these changes
Gran trabajo Diego, funciona a la perfección, seguro que a nuestros usuarios piloto les encanta ver como aplicamos las mejoras que nos proponen ¡Enhorabuena!

2024-04-09 13:41 UTC, alesanfe approved these changes
¡Todo funciona a la perfección!

2024-04-09 14:00 UTC, antcardia approved these changes
¡Buen trabajo! Todo funciona correctamente.

2024-04-09 14:00 UTC, merged