Feature/365 feature mejoras up s3 5
G12-ISPP/ISPP pull request #396
Opened 2024-04-08 17:10 UTC by ursgarsan

## Mejoras de usuario 5 #365 

### Descripción

Se han resuelto las mejoras de usuario 24, 25, 29, 30, 32 que consisten en:

- Hacer que el email sea único: se ha implementado en el registro de usuario y  ya sale un mensaje donde se indica que el email ya está registrado en el sistema.
- No introducir caracteres numéricos en los campos de ciudad, nombre y apellidos de todo el sistema.
- Hacer que no aparezca el botón de añadir opinión cuando accedemos a nuestro propio perfil.
- Limpiados console.log del apartado de comunidad.
- Si accedemos a un usuario desde uno de sus productos deben aparecer sus productos.

### Contexto Adicional

No aplica

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [x] He revisado y resuelto cualquier conflicto de fusión.
- [x] He actualizado la documentación.

2024-04-08 17:41 UTC, alesanfe approved these changes
- Si intento usar el mismo correo para registrarme otra vez, el sistema me bloquea y no me deja.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/3a37d2b8-3ae6-4439-9cab-ec853a9e3f76)

- Funciona de maravilla, no me deja ingresar números donde no corresponden. Me ayuda a evitar errores.

- Está genial, el botón desaparece automáticamente cuando ya estoy logueado, así no hay confusión.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/0b4405fd-117a-4c4a-947e-cf317d607eb6)

- Tal vez sería buena idea extender esta funcionalidad a más partes del programa, tanto en el backend como en el frontend.

- En la imagen en la que mostraba los dos usuarios, se veía que se podían acceder a los productos que ha añadido un usuario a la aplicaicón, por tanto, funciona correctamente.

2024-04-08 19:43 UTC, jucamgar2 requested changes
Con esta modificación hay test que han dejado de funcionar @ursgarsan por favor solucionalos

2024-04-09 13:58 UTC, ursgarsan commented
Ya con estas modificaciones quedan arreglados los test de backend @jucamgar2 !

2024-04-09 14:02 UTC, jucamgar2 approved these changes
Muchas gracias Ursula, una vez arreglado eso, está todo perfecto

2024-04-09 14:11 UTC, merged