Feat: listado de reportes de producto
G12-ISPP/ISPP pull request #400
Opened 2024-04-09 14:29 UTC by mariaescalante

## Listado de reportes de productos #338

### Descripción

Se ha implementado un listado de reportes de productos solo visibles para usuarios administradores. Se encuentra en el panel de administrador
![image](https://github.com/G12-ISPP/ISPP/assets/73230133/3bc6a1f9-0676-4ddc-b42b-04b72bff2341)

### Contexto Adicional

![image](https://github.com/G12-ISPP/ISPP/assets/73230133/ef5c1377-a5fd-415f-bc69-f19eef6da3de)
## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-04-09 15:03 UTC, antcardia requested changes
Funciona correctamente, pero ten cuidado a la hora de nombrar los estilos, porque se comparten nombres con otros estilos anteriormente definidos. Te recomiendo que le pongas estos nombres:
![image](https://github.com/G12-ISPP/ISPP/assets/72875624/20afecef-e502-4288-8f5b-e62038a51ea6)
.reports-list y .report-card

2024-04-11 13:53 UTC, antcardia approved these changes
Ya funciona correctamente. ¡Buen trabajo María!

2024-04-11 13:58 UTC, jucamgar2 approved these changes
Gran trabajo María, con la corrección ha quedado todo perfecto!!

2024-04-11 14:01 UTC, PabloMera6 approved these changes
Funciona correctamente María, enhorabuena

2024-04-11 14:05 UTC, merged