feature/375 reportes de usuarios
G12-ISPP/ISPP pull request #405
Opened 2024-04-09 20:44 UTC by Alejandrocg024

## Reportes de usuarios #375 

### Descripción
Se ha creado la funcionalidad correspondiente a los reportes de usuario

### Contexto Adicional
Se puede ver el botón de reportar:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/709a8bc0-3c11-4b01-8f04-df9869fc838a)

Y el modal que se abre para realizar el reporte:
![image](https://github.com/G12-ISPP/ISPP/assets/72875687/8123dc78-8678-4138-88a0-2b5774621226)

También se puede ver que la restricción para que no se pueda realizar dos reportes a un mismo usuario con el fin de evitar spam

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [X] He probado exhaustivamente estos cambios localmente.
- [ ] He revisado y resuelto cualquier conflicto de fusión.
- [ ] He actualizado la documentación.

2024-04-09 20:48 UTC, jucamgar2 requested changes
Funciona a la perfección y me encata como sigue el concepto de reportar un producto, pero me encantaría que añadas como campo a los reportes una foto para que así se pueda demostrar el porque del reporte

2024-04-10 16:41 UTC, Alejandrocg024 commented
Se ha implementado la opción de que se pueda añadir una imagen al reporte.

Como adicional, se ha añadido también al reporte de productos.

2024-04-10 19:20 UTC, davra02 approved these changes
Gracias por la funcionalidad Alejandro. Gran trabajo. Además me gusta la estética del modal y la validación de usuario reportado funciona correctamente. ¡Enhorabuena!

2024-04-11 02:42 UTC, davcorrom approved these changes
Buen trabajo Alejandro. Tras haber estado probando la funcionalidad, no me he encontrado con ningún problema. ¡Enhorabuena!

2024-04-11 14:34 UTC, Alejandrocg024 commented
Se van a tener que modificar por completo varios tests

2024-04-11 15:49 UTC, carloosbaquero approved these changes
Me ha gustado mucho como has implementado la funcionalidad, está todo genial!

2024-04-11 15:50 UTC, merged